# Things to change 
# logger project name, 
# model checkpoint dir + filename 
# model settings 
seed_everything: 0

trainer:
  max_epochs: 100
  accelerator: auto
  strategy: auto
  devices: auto
  check_val_every_n_epoch: 1
  log_every_n_steps: 20
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: decoder_initial_runs_rosa
      log_model: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/decoder/dscnet_decoder/
        filename: tm_tiny_dscnet_decoder
        monitor: val/mIoU
        mode: max
        save_top_k: 1
        save_last: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 5
        mode: min
    - class_path: custom_modules.callbacks.PredictionWriter
      init_args:
        output_dir: /kaggle/working/predictions/panels
        rgb_key: S2L2A
        rgb_indices: [0, 1, 2]
        positive_class: 1
        filename_stat: iou
  enable_checkpointing: true

model:
  class_path: terratorch.tasks.SemanticSegmentationTask
  init_args:
    model_factory: EncoderDecoderFactory
    model_args:
      backbone: terramind_v1_tiny
      backbone_img_size: 256
      backbone_pretrained: true
      backbone_modalities:
        - S2L2A 
        - S1GRD
      backbone_bands:
        S2L2A: # order does matter here.
          - RED
          - GREEN
          - BLUE
          - RED_EDGE_1
          - RED_EDGE_2
          - RED_EDGE_3
          - NIR_NARROW
          - NIR_BROAD
          - SWIR_1
          - SWIR_2
        S1GRD:
          - VV
          - VH
      necks:
        - name: SelectIndices
          indices: [2, 5, 8, 11]
        - name: ReshapeTokensToImage
        - name: LearnedInterpolateToPyramidal
      decoder: TerraTorchDSCNetDecoder
      decoder_channels: [256, 128, 64, 32]
      num_classes: 2
    loss: dice
    ignore_index: -1
    freeze_backbone: false
    optimizer: AdamW
    lr: 2.763941973761204e-05
    scheduler: ReduceLROnPlateau
    scheduler_hparams:
      patience: 4
      factor: 0.5
    class_names: ["Background", "Road"]
    plot_on_val: false
    tiled_inference_parameters:
      h_crop: 256
      w_crop: 256
      h_stride: 256
      w_stride: 256
      delta: 0
      batch_size: 8          # chips per forward, independent of the dataloader
      blend_overlaps: false
      average_patches: false
      padding: reflect
      verbose: false

data: ../../prelim_experiments/config/augment_data/augmented_data.yml